Revert "pytest tests/test_encassist.py: workaroudn E   AttributeError: partially initialized module 'saltgang.encassist' has no attribute 'add_parser' (most likely due to a circular import)"
This reverts commit 8e6ed77b027b5b70e8cc9accb789eec2b23c7471.