pytest tests/test_encassist.py: workaroudn E   AttributeError: partially initialized module 'saltgang.encassist' has no attribute 'add_parser' (most likely due to a circular import)